create table PESSOA_FISICA(
	CPF VARCHAR(20) NOT NULL,
	IDENTIDADE VARCHAR(20) NOT NULL,
	ID_PES_FISICA SERIAL NOT NULL,
	PRIMARY KEY(ID_PES_FISICA)
);

CREATE TABLE PESSOA_JURIDICA(
	CNPJ VARCHAR(20) NOT NULL,
	RAZAO_SOCIAL VARCHAR(20),
	ID_PES_JURIDICA SERIAL NOT NULL,
	PRIMARY KEY(ID_PES_JURIDICA)
);

CREATE TABLE PESSOA(
	NOME VARCHAR(20) NOT NULL,
	IDENTIDADE VARCHAR(20) NOT NULL,
	RUA VARCHAR(50) NOT NULL,
	NUMERO INTEGER NOT NULL,
	CEP VARCHAR(20),
	CIDADE SERIAL NOT NULL,
	ESTADO VARCHAR(20),
	JURIDICA SERIAL,
	FISICA SERIAL,
	ID_PESSOA SERIAL NOT NULL,
	PRIMARY KEY(ID_PESSOA),
	
	FOREIGN KEY (JURIDICA) REFERENCES PESSOA_JURIDICA(ID_PES_JURIDICA),
	FOREIGN KEY (FISICA) REFERENCES PESSOA_FISICA(ID_PES_FISICA),
	FOREIGN KEY (CIDADE) REFERENCES CIDADE(ID_CIDADE)
);

CREATE TABLE CIDADE(
	NOME VARCHAR(30) NOT NULL,
	ESTADO SERIAL NOT NULL,
	ID_CIDADE SERIAL NOT NULL,
	PRIMARY KEY(ID_CIDADE),
	
	FOREIGN KEY (ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE ESTADO(
	NOME VARCHAR(30) NOT NULL,
	ID_ESTADO SERIAL NOT NULL,
	PRIMARY KEY(ID_ESTADO)
);

CREATE TABLE CLIENTE(
	DATA_ANIVERSARIO DATE,
	NUMERO_CONTATO VARCHAR(20),
	PESSOA SERIAL NOT NULL,
	ID_CLIENTE SERIAL NOT NULL,
	PRIMARY KEY(ID_CLIENTE),
	
	FOREIGN KEY (PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE VENDEDOR(
	COMISSAO INTEGER NOT NULL CHECK (COMISSAO>0),
	PESSOA INTEGER NOT NULL,
	ID_VENDEDOR SERIAL NOT NULL,
	PRIMARY KEY(ID_VENDEDOR),
	
	FOREIGN KEY(PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE FORNECEDOR(
	NOME VARCHAR(30) NOT NULL UNIQUE,
	TELEFONE INTEGER NOT NULL,
	SETOR VARCHAR(30) NOT NULL,
	PESSOA SERIAL NOT NULL,
	ID_FORNECEDOR SERIAL NOT NULL,
	PRIMARY KEY(ID_FORNECEDOR),
	
	FOREIGN KEY (PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

CREATE TABLE PEDIDOS(
	DATA_PEDIDO DATE NOT NULL,
	QUANT_PARCELAS INTEGER NOT NULL CHECK (QUANT_PARCELAS>0),
	CLIENTE SERIAL NOT NULL,
	VENDEDOR SERIAL NOT NULL,
	ID_PAGAMENTO SERIAL NOT NULL,
	ID_PEDIDO SERIAL NOT NULL,
	PRIMARY KEY(ID_PEDIDO),
	
	FOREIGN KEY(CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	FOREIGN KEY(VENDEDOR) REFERENCES VENDEDOR(ID_VENDEDOR),
	FOREIGN KEY(ID_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_PAGAMENTO)
);


CREATE TABLE VENDA_PEDIDO(
	QUANTIDADE INTEGER NOT NULL CHECK (QUANTIDADE>0),
	VALOR_PECA INT NOT NULL CHECK (VALOR_PECA>0),
	PEDIDO SERIAL NOT NULL,
	PECASSS SERIAL  NOT NULL,
	ESTOQUEE SERIAL NOT NULL,
	
	FOREIGN KEY (PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO),
	FOREIGN KEY (PECASSS) REFERENCES PECAS(ID_PECA),
	FOREIGN KEY (ESTOQUEE) REFERENCES ESTOQUE(ID_ESTOQUE)
);

CREATE TABLE PECAS(
	DESCRICAO VARCHAR(20),
	VALOR INT NOT NULL CHECK (VALOR>0),
	FORNECEDOR INTEGER NOT NULL,
	ID_PECA INTEGER NOT NULL,
	PRIMARY KEY(ID_PECA),
	
	FOREIGN KEY (FORNECEDOR) REFERENCES FORNECEDOR(ID_FORNECEDOR)
);

CREATE TABLE PAGAMANTO_PARCELA(
	RECEBIDO BOOLEAN NOT NULL DEFAULT '0',
	DATA_PAG DATE NOT NULL,
	VALOR_PARCELA INT NOT NULL CHECK (VALOR_PARCELA>0),
	PEDIDO_FORN INTEGER NOT NULL,
	FORMA_PAGAMENTO INTEGER NOT NULL,
	DATA_VENC DATE NOT NULL,
	PRIMARY KEY(DATA_VENC),
	
	FOREIGN KEY(PEDIDO_FORN) REFERENCES PEDIDO_FORN(ID_PEDIDO_FORN),
	FOREIGN KEY(FORMA_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_PAGAMENTO)
);

CREATE TABLE ESTOQUE(
 	DESCRICAO VARCHAR(50) NOT NULL,
 	ID_ESTOQUE SERIAL NOT NULL,
	PRIMARY KEY(ID_ESTOQUE)
);

CREATE TABLE ARMAZENAMENTO(
	QUANTIDADE INTEGER NOT NULL CHECK (QUANTIDADE>=0),
	PECAS INTEGER NOT NULL,
	ESTOQUE INTEGER NOT NULL,
	FOREIGN KEY (PECAS) REFERENCES PECAS(ID_PECA),
	FOREIGN KEY (ESTOQUE) REFERENCES ESTOQUE(ID_ESTOQUE)
);

CREATE TABLE PEDIDO_FORN(
	QUANTIDADE INTEGER NOT NULL,
	VALOR_PECA INT NOT NULL CHECK (VALOR_PECA>0),
	DATA_PEDIDO DATE NOT NULL,
	QUANT_PARCELAS INTEGER NOT NULL CHECK (QUANT_PARCELAS>0),
	PECAS SERIAL NOT NULL,
	ID_PEDIDO_FORN SERIAL NOT NULL,
	PRIMARY KEY(ID_PEDIDO_FORN),
	
	FOREIGN KEY (PECAS) REFERENCES PECAS(ID_PECA)
);

CREATE TABLE FORMA_PAGAMENTO(
	DESCRICAO VARCHAR(50) NOT NULL,
	ID_PAGAMENTO SERIAL NOT NULL,
	PRIMARY KEY(ID_PAGAMENTO)
);

CREATE TABLE PAGAMENTO_DAS_PARCELAS(
	RECEBIDO BOOLEAN NOT NULL DEFAULT '0',
	DATA_PAGAMENTO_PARCELA DATE NOT NULL,
	VALOR_PARCELA INTEGER NOT NULL CHECK (VALOR_PECA>0),
	ID_PEDIDO INTEGER NOT NULL,
	ID_PAGAMENTO INTEGER NOT NULL,
	DATA_VENCIMENTO_PARCELA DATE NOT NULL,
	PRIMARY KEY(DATA_VENCIMENTO_PARCELA),
	
	FOREIGN KEY (ID_PAGAMENTO) REFERENCES FORMA_PAGAMENTO(ID_PAGAMENTO),
	FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDOS(ID_PEDIDO)
);

ALTER TABLE PESSOA_FISICA ADD COLUMN RG VARCHAR(20)

ALTER TABLE PESSOA_JURIDICA ADD COLUMN IE VARCHAR(15)

ALTER TABLE PESSOA ADD CONSTRAINT UNIQUE(NOME)

ALTER TABLE PESSOA RENAME NUMERO TO CELULAR

CREATE TABLE TELEFONE(
	NUMERO VARCHAR(20) NOT NULL UNIQUE,
	PESSOA INTEGER NOT NULL,
	FOREIGN KEY (PESSOA) REFERENCES PESSOA(ID_PESSOA)
);

ALTER TABLE VENDEDOR ADD CHECK (COMISSAO>=5)

ALTER TABLE VENDEDOR ADD COLUMN DATA_ACERTO_COMISSAO DATE NOT NULL

ALTER TABLE VENDEDOR ALTER COLUMN DATA_ACERTO_COMISSAO DROP NOT NULL

ALTER TABLE PESSOA ADD COLUMN ATIVO BOOLEAN DEFAULT '1'

ALTER TABLE PESSOA_JURIDIAC ALTER COLUMN IE TYPE INTEGER

ALTER TABLE PESSOA_JURIDICA RENAME IE TO INSCRICAO_ESTADUAL

ALTER TABLE PESSOA_FISICA ALTER COLUMN RG TYPE VARCHAR(25)

ALTER TABLE PESSOA RENAME CIDADE TO ID_CIDADE_PESSOA

DROP COLUMN VENDA_PEDIDO
DROP COLUMN ARMAZENAMENTO
DROP COLUMN PAGAMENTO_PARCELAS
DROP COLUMN ESTOQUE
DROP COLUMN FORMA_PAGAMENTO
DROP COLUMN PEDIDO_FORN
DROP COLUMN PAGAMENTO_DAS_PARCELAS
DROP COLUMN PEDIDOS
DROP COLUMN PECAS
DROP COLUMN VENDEDOR
DROP COLUMN CLIENTE
DROP COLUMN FORNECEDOR
DROP COLUMN PESSOA
DROP COLUMN PESSOA_FISICA
DROP COLUMN PESSOA_JURIDICA
